### ISSUE TITLE
Keywords aliases

### ISSUE THREAD

**Issue by alemuller** [rydesun/tree-sitter-dot#1]
The keywords could be aliased to a string.

Instead of:
```js
alias(ignoreCase('strict'), $.keyword),
```
I think it would be better to:
```js
alias(ignoreCase('strict'), "strict"),
```

This allows  keywords to be captured with their names on the schemes.

**Comment by rydesun** [comment]
Thanks! It does make capturing a little easier.
Does that PR meet your demands?

**Comment by alemuller** [comment]
It does, thank you.

You may need to change the query on nvim-treesitter.
